### ISSUE TITLE
Voorbeeld JSON-LD versie lijst met UIDs

### ISSUE THREAD

**Issue by FMJansen** [Opwiekanikstemmen-nl/data#1]

**Comment by MPvHarmelen** [comment]
FYI: dit wil ik gaan gebruiken: https://json-ld.org/

**Comment by MPvHarmelen** [comment]
We kunnen bestaande IRIs voor mensen gebruiken die op Wikipedia voorkomen, zie https://triplydb.com/DBpedia-association/dbpedia/browser?resource=http%3A%2F%2Fdbpedia.org%2Fresource%2FMark_Rutte

**Comment by MPvHarmelen** [comment]
[Deze query](https://dbpedia.org/sparql?default-graph-uri=http%3A%2F%2Fdbpedia.org&query=PREFIX+dbp%3A+%3Chttp%3A%2F%2Fdbpedia.org%2Fproperty%2F%3E%0D%0APREFIX+dbt%3A+%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2FTemplate%3A%3E%0D%0APREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0D%0Aselect+*+where++%7B%0D%0A++%3Fs+dbp%3AwikiPageUsesTemplate+dbt%3APolitical_parties_in_the_Netherlands%0D%0A%7D+limit+100%0D%0A&format=text%2Fhtml&timeout=30000&signal_void=on&signal_unconnected=on) geeft een lijstje van politieke partijen in Nederland die op wikipedia staan?

```sparql
PREFIX dbp: <http://dbpedia.org/property/>
PREFIX dbt: <http://dbpedia.org/resource/Template:>
select * where  {
  ?s dbp:wikiPageUsesTemplate dbt:Political_parties_in_the_Netherlands
} limit 100
```

**Comment by MPvHarmelen** [comment]
Zie trouwens ook: https://data.overheid.nl/dataset/linked-data-overheid

**Comment by MPvHarmelen** [comment]
Data van de tweede kamer:

https://gegevensmagazijn.tweedekamer.nl/OData/v4/2.0/Persoon?$filter=Verwijderd%20eq%20false%20and%20(Functie%20eq%20%27Eerste%20Kamerlid%27%20or%20Functie%20eq%20%27Tweede%20Kamerlid%27)

**Comment by MPvHarmelen** [comment]
[Conversie van 2e-kamer JSON naar linked data met JSON-LD voorbeeld](https://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22%40context%22%3A%7B%22Id%22%3A%22%40id%22%2C%22Nummer%22%3A%22http%3A%2F%2Fofficiele-iri-voor-nummer%22%2C%22value%22%3A%22%40graph%22%2C%22%40base%22%3A%22https%3A%2F%2Fgegevensmagazijn.tweedekamer.nl%2FOData%2Fv4%2F2.0%2FPersoon%2F%22%7D%2C%22%40odata.context%22%3A%22https%3A%2F%2Fgegevensmagazijn.tweedekamer.nl%2FOData%2Fv4%2F2.0%2F%24metadata%23Persoon%22%2C%22value%22%3A%5B%7B%22Id%22%3A%22e55ca731-e1aa-44c0-a5f3-0008c23976f7%22%2C%22Nummer%22%3A1034%2C%22Titels%22%3Anull%2C%22Initialen%22%3A%22J.J.%22%2C%22Tussenvoegsel%22%3Anull%2C%22Achternaam%22%3A%22Atsma%22%2C%22Voornamen%22%3A%22Joop%22%2C%22Roepnaam%22%3A%22Joop%22%2C%22Geslacht%22%3A%22man%22%2C%22Functie%22%3A%22Eerste%20Kamerlid%22%2C%22Geboortedatum%22%3A%221956-07-06T00%3A00%3A00%2B02%3A00%22%2C%22Geboorteplaats%22%3A%22Surhuisterveen%22%2C%22Geboorteland%22%3Anull%2C%22Overlijdensdatum%22%3Anull%2C%22Overlijdensplaats%22%3Anull%2C%22Woonplaats%22%3A%22Surhuisterveen%22%2C%22Land%22%3A%22NL%22%2C%22Fractielabel%22%3A%22CDA%22%2C%22ContentType%22%3A%22image%2Fjpeg%22%2C%22ContentLength%22%3A27853%2C%22GewijzigdOp%22%3A%222023-08-29T13%3A09%3A45%2B02%3A00%22%2C%22ApiGewijzigdOp%22%3A%222023-08-29T11%3A15%3A19.4179601Z%22%2C%22Verwijderd%22%3Afalse%7D%2C%7B%22Id%22%3A%221c889902-6ede-427c-8682-000f683fffaa%22%2C%22Nummer%22%3A2491%2C%22Titels%22%3A%22MA%22%2C%22Initialen%22%3A%22M.%22%2C%22Tussenvoegsel%22%3Anull%2C%22Achternaam%22%3A%22Agema%22%2C%22Voornamen%22%3A%22Marie-Fleur%22%2C%22Roepnaam%22%3A%22Fleur%22%2C%22Geslacht%22%3A%22vrouw%22%2C%22Functie%22%3A%22Tweede%20Kamerlid%22%2C%22Geboortedatum%22%3A%221976-09-16T00%3A00%3A00%2B02%3A00%22%2C%22Geboorteplaats%22%3A%22Purmerend%22%2C%22Geboorteland%22%3A%22Nederland%22%2C%22Overlijdensdatum%22%3Anull%2C%22Overlijdensplaats%22%3Anull%2C%22Woonplaats%22%3A%22's-Gravenhage%22%2C%22Land%22%3A%22NL%22%2C%22Fractielabel%22%3Anull%2C%22ContentType%22%3A%22image%2Fjpeg%22%2C%22ContentLength%22%3A52759%2C%22GewijzigdOp%22%3A%222023-08-29T13%3A09%3A47%2B02%3A00%22%2C%22ApiGewijzigdOp%22%3A%222023-08-29T11%3A22%3A31.8477812Z%22%2C%22Verwijderd%22%3Afalse%7D%5D%7D&context=%7B%22%40context%22%3A%7B%22name%22%3A%22http%3A%2F%2Frdf.data-vocabulary.org%2F%23name%22%2C%22ingredient%22%3A%22http%3A%2F%2Frdf.data-vocabulary.org%2F%23ingredients%22%2C%22yield%22%3A%22http%3A%2F%2Frdf.data-vocabulary.org%2F%23yield%22%2C%22instructions%22%3A%22http%3A%2F%2Frdf.data-vocabulary.org%2F%23instructions%22%2C%22step%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Frdf.data-vocabulary.org%2F%23step%22%2C%22%40type%22%3A%22xsd%3Ainteger%22%7D%2C%22description%22%3A%22http%3A%2F%2Frdf.data-vocabulary.org%2F%23description%22%2C%22xsd%22%3A%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%22%7D%7D):

```json
{
  	"@context": {
      "Id": "@id",
      "Nummer": "http://officiele-iri-voor-nummer",
      "value": "@graph",
      "@base": "https://gegevensmagazijn.tweedekamer.nl/OData/v4/2.0/Persoon/"
    },
    "@odata.context": "https://gegevensmagazijn.tweedekamer.nl/OData/v4/2.0/$metadata#Persoon",
    "value": [
        {
            "Id": "e55ca731-e1aa-44c0-a5f3-0008c23976f7",
            "Nummer": 1034,
            "Titels": null,
            "Initialen": "J.J.",
            "Tussenvoegsel": null,
            "Achternaam": "Atsma",
            "Voornamen": "Joop",
            "Roepnaam": "Joop",
            "Geslacht": "man",
            "Functie": "Eerste Kamerlid",
            "Geboortedatum": "1956-07-06T00:00:00+02:00",
            "Geboorteplaats": "Surhuisterveen",
            "Geboorteland": null,
            "Overlijdensdatum": null,
            "Overlijdensplaats": null,
            "Woonplaats": "Surhuisterveen",
            "Land": "NL",
            "Fractielabel": "CDA",
            "ContentType": "image/jpeg",
            "ContentLength": 27853,
            "GewijzigdOp": "2023-08-29T13:09:45+02:00",
            "ApiGewijzigdOp": "2023-08-29T11:15:19.4179601Z",
            "Verwijderd": false
        },
        {
            "Id": "1c889902-6ede-427c-8682-000f683fffaa",
            "Nummer": 2491,
            "Titels": "MA",
            "Initialen": "M.",
            "Tussenvoegsel": null,
            "Achternaam": "Agema",
            "Voornamen": "Marie-Fleur",
            "Roepnaam": "Fleur",
            "Geslacht": "vrouw",
            "Functie": "Tweede Kamerlid",
            "Geboortedatum": "1976-09-16T00:00:00+02:00",
            "Geboorteplaats": "Purmerend",
            "Geboorteland": "Nederland",
            "Overlijdensdatum": null,
            "Overlijdensplaats": null,
            "Woonplaats": "'s-Gravenhage",
            "Land": "NL",
            "Fractielabel": null,
            "ContentType": "image/jpeg",
            "ContentLength": 52759,
            "GewijzigdOp": "2023-08-29T13:09:47+02:00",
            "ApiGewijzigdOp": "2023-08-29T11:22:31.8477812Z",
            "Verwijderd": false
        }
      ]
}
```

**Comment by MPvHarmelen** [comment]
We willen sws ook trouwens deze vocabulaire gebruiken: http://xmlns.com/foaf/0.1/
